-- MySQL Script generated by MySQL Workbench
-- mer. 22 nov. 2023 15:15:43
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema compta
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema compta
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `compta` DEFAULT CHARACTER SET utf8 ;
USE `compta` ;

-- -----------------------------------------------------
-- Table `compta`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compta`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `adresse` VARCHAR(45) NULL,
  `mobile` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compta`.`fournisseur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compta`.`fournisseur` (
  `fournisseur_id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `adresse` VARCHAR(45) NULL,
  `siren` VARCHAR(45) NULL,
  `nom_entreprise` VARCHAR(45) NULL,
  PRIMARY KEY (`fournisseur_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compta`.`facture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compta`.`facture` (
  `facture_id` INT NOT NULL AUTO_INCREMENT,
  `date_facture` DATE NULL,
  `numero_facture` VARCHAR(45) NULL,
  `designation` VARCHAR(45) NULL,
  `code_produit` VARCHAR(45) NULL,
  `quantité` VARCHAR(45) NULL,
  `prix_unitaire` VARCHAR(45) NULL,
  `montant HT` VARCHAR(45) NULL,
  `remise` VARCHAR(45) NULL,
  `TVA` VARCHAR(45) NULL,
  `montant TTC` VARCHAR(45) NULL,
  `fournisseur_fournisseur_id` INT NOT NULL,
  PRIMARY KEY (`facture_id`, `fournisseur_fournisseur_id`),
  INDEX `fk_facture_fournisseur1_idx` (`fournisseur_fournisseur_id` ASC) VISIBLE,
  CONSTRAINT `fk_facture_fournisseur1`
    FOREIGN KEY (`fournisseur_fournisseur_id`)
    REFERENCES `compta`.`fournisseur` (`fournisseur_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compta`.`user_has_facture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compta`.`user_has_facture` (
  `user_user_id` INT NOT NULL,
  `facture_facture_id` INT NOT NULL,
  PRIMARY KEY (`user_user_id`, `facture_facture_id`),
  INDEX `fk_user_has_facture_facture1_idx` (`facture_facture_id` ASC) VISIBLE,
  INDEX `fk_user_has_facture_user_idx` (`user_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_facture_user`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `compta`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_has_facture_facture1`
    FOREIGN KEY (`facture_facture_id`)
    REFERENCES `compta`.`facture` (`facture_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compta`.`secteur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compta`.`secteur` (
  `secteur_id` INT NOT NULL,
  `nom_secteur` VARCHAR(45) NULL,
  `code_secteur` VARCHAR(45) NULL,
  PRIMARY KEY (`secteur_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compta`.`fournisseur_has_secteur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compta`.`fournisseur_has_secteur` (
  `fournisseur_fournisseur_id` INT NOT NULL,
  `secteur_secteur_id` INT NOT NULL,
  PRIMARY KEY (`fournisseur_fournisseur_id`, `secteur_secteur_id`),
  INDEX `fk_fournisseur_has_secteur_secteur1_idx` (`secteur_secteur_id` ASC) VISIBLE,
  INDEX `fk_fournisseur_has_secteur_fournisseur1_idx` (`fournisseur_fournisseur_id` ASC) VISIBLE,
  CONSTRAINT `fk_fournisseur_has_secteur_fournisseur1`
    FOREIGN KEY (`fournisseur_fournisseur_id`)
    REFERENCES `compta`.`fournisseur` (`fournisseur_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_fournisseur_has_secteur_secteur1`
    FOREIGN KEY (`secteur_secteur_id`)
    REFERENCES `compta`.`secteur` (`secteur_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compta`.`station_essence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compta`.`station_essence` (
  `station_essence_id` INT NOT NULL,
  `nom_station` VARCHAR(45) NULL,
  `adresse` VARCHAR(45) NULL,
  `siren` VARCHAR(45) NULL,
  `secteur_secteur_id` INT NOT NULL,
  PRIMARY KEY (`station_essence_id`, `secteur_secteur_id`),
  INDEX `fk_station_essence_secteur1_idx` (`secteur_secteur_id` ASC) VISIBLE,
  CONSTRAINT `fk_station_essence_secteur1`
    FOREIGN KEY (`secteur_secteur_id`)
    REFERENCES `compta`.`secteur` (`secteur_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
